# Generated by Django 2.1.1 on 2018-09-01 13:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(max_length=128, unique=True, verbose_name='kod próbki')),
                ('name', models.CharField(max_length=500, verbose_name='nazwa')),
                ('amount', models.IntegerField(verbose_name='ilość opakowań')),
                ('mass', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='masa próbki')),
                ('MSDS', models.BooleanField(choices=[(0, 'Nie'), (1, 'Tak')], verbose_name='dołączony MSDS?')),
                ('TDS', models.BooleanField(choices=[(0, 'Nie'), (1, 'Tak')], verbose_name='dołączony TDS?')),
                ('location', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], max_length=50, verbose_name='miejsce składowania')),
                ('date_received', models.DateField(default=datetime.date.today, verbose_name='data przyjęcia')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier', verbose_name='dostawca'),
        ),
        migrations.AddField(
            model_name='sample',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('deleted user'), to=settings.AUTH_USER_MODEL, verbose_name='podpis'),
        ),
    ]
