# Generated by Django 2.1.1 on 2018-09-04 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='location',
            field=models.CharField(choices=[('1', 'pokój nr 1'), ('2', 'pokój nr 2'), ('3', 'pokój nr 3'), ('4', 'pokój nr 4'), ('5', 'pokój nr 5'), ('6', 'pokój nr 6'), ('7', 'pokój nr 7'), ('8', 'pokój nr 8')], max_length=50, verbose_name='miejsce składowania'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='mass',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='masa próbki w kg'),
        ),
    ]
