# Generated by Django 2.1.1 on 2018-09-10 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180904_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='barcode',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='photo',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
